ALTER TABLE order_items ADD COLUMN preparation_started_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE order_items ADD COLUMN ready_at TIMESTAMP WITHOUT TIME ZONE;
ALTER TABLE order_items ADD COLUMN delivered_at TIMESTAMP WITHOUT TIME ZONE;
